-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 21:50:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gamedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gamedb` ;

-- -----------------------------------------------------
-- Schema gamedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamedb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema scpdnd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scpdnd` ;

-- -----------------------------------------------------
-- Schema scpdnd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scpdnd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gamedb` ;

-- -----------------------------------------------------
-- Table `gamedb`.`accesscard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`accesscard` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`accesscard` (
  `card_id` VARCHAR(255) NOT NULL,
  `status_id` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `expire` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`card_id`),
  INDEX `accessCard_status` (`status_id` ASC) VISIBLE,
  INDEX `accessCard_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `accessCard_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `gamedb`.`accessstatus` (`id`),
  CONSTRAINT `accessCard_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all cards (passes)';


-- -----------------------------------------------------
-- Table `gamedb`.`accessstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`accessstatus` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`accessstatus` (
  `id` INT NOT NULL,
  `name` CHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible access statuses';


-- -----------------------------------------------------
-- Table `gamedb`.`clearance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`clearance` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`clearance` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible clearance levels';


-- -----------------------------------------------------
-- Table `gamedb`.`containmentclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`containmentclass` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`containmentclass` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible containment classes';


-- -----------------------------------------------------
-- Table `gamedb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`department` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`department` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all departments of the Foundation';


-- -----------------------------------------------------
-- Table `gamedb`.`disruptionclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`disruptionclass` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`disruptionclass` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible disruption classes';


-- -----------------------------------------------------
-- Table `gamedb`.`doctype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`doctype` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`doctype` (
  `id` INT NOT NULL,
  `name` INT NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible document types';


-- -----------------------------------------------------
-- Table `gamedb`.`employeeclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`employeeclass` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`employeeclass` (
  `id` INT NOT NULL,
  `letter` VARCHAR(1) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `letter` (`letter` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible staff classes';


-- -----------------------------------------------------
-- Table `gamedb`.`facility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`facility` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`facility` (
  `id` INT NOT NULL,
  `width` DOUBLE NOT NULL,
  `length` DOUBLE NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `facilityType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `facility_facilityType` (`facilityType_id` ASC) VISIBLE,
  CONSTRAINT `facility_facilityType`
    FOREIGN KEY (`facilityType_id`)
    REFERENCES `gamedb`.`facilitytype` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all the Foundation\'\'s facilities';


-- -----------------------------------------------------
-- Table `gamedb`.`facilitysection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`facilitysection` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`facilitysection` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `sectionType_id` INT NOT NULL,
  `safetyRequirements` TEXT NOT NULL,
  `facility_id` INT NOT NULL,
  `clearance_id` INT NOT NULL,
  `sectionStatus_id` INT NOT NULL,
  `specialAccessRequired` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `facilitySection_SectionType` (`sectionType_id` ASC) VISIBLE,
  INDEX `facilitySection_clearance` (`clearance_id` ASC) VISIBLE,
  INDEX `facilitySection_facility` (`facility_id` ASC) VISIBLE,
  INDEX `facilitySection_roomStatus` (`sectionStatus_id` ASC) VISIBLE,
  CONSTRAINT `facilitySection_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`),
  CONSTRAINT `facilitySection_facility`
    FOREIGN KEY (`facility_id`)
    REFERENCES `gamedb`.`facility` (`id`),
  CONSTRAINT `facilitySection_roomStatus`
    FOREIGN KEY (`sectionStatus_id`)
    REFERENCES `gamedb`.`roomstatus` (`id`),
  CONSTRAINT `facilitySection_SectionType`
    FOREIGN KEY (`sectionType_id`)
    REFERENCES `gamedb`.`sectiontype` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all sections within the facilities';


-- -----------------------------------------------------
-- Table `gamedb`.`facilitytype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`facilitytype` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`facilitytype` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible facility types';


-- -----------------------------------------------------
-- Table `gamedb`.`fileaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`fileaccess` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`fileaccess` (
  `fileType_id` INT NOT NULL,
  `fileAccessType_id` INT NOT NULL,
  `fileRequester_fileRequesterType_id` INT NOT NULL,
  `fileRequester_fileRequester_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`fileType_id`, `fileAccessType_id`, `fileRequester_fileRequesterType_id`, `fileRequester_fileRequester_id`),
  INDEX `fileAccess_fileAccessType` (`fileAccessType_id` ASC) VISIBLE,
  INDEX `fileAccess_fileRequester` (`fileRequester_fileRequesterType_id` ASC, `fileRequester_fileRequester_id` ASC) VISIBLE,
  CONSTRAINT `fileAccess_fileAccessType`
    FOREIGN KEY (`fileAccessType_id`)
    REFERENCES `gamedb`.`fileaccesstype` (`id`),
  CONSTRAINT `fileAccess_fileRequester`
    FOREIGN KEY (`fileRequester_fileRequesterType_id` , `fileRequester_fileRequester_id`)
    REFERENCES `gamedb`.`filerequester` (`fileRequesterType_id` , `fileRequester_id`),
  CONSTRAINT `fileAccess_fileType`
    FOREIGN KEY (`fileType_id`)
    REFERENCES `gamedb`.`filetype` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all file permissions';


-- -----------------------------------------------------
-- Table `gamedb`.`fileaccesstype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`fileaccesstype` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`fileaccesstype` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible file access types';


-- -----------------------------------------------------
-- Table `gamedb`.`filerequester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`filerequester` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`filerequester` (
  `fileRequesterType_id` INT NOT NULL,
  `fileRequester_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`fileRequesterType_id`, `fileRequester_id`),
  CONSTRAINT `fileRequester_fileRequesterType`
    FOREIGN KEY (`fileRequesterType_id`)
    REFERENCES `gamedb`.`filerequestertype` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamedb`.`filerequestertype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`filerequestertype` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`filerequestertype` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible types of user-to-file relationships';


-- -----------------------------------------------------
-- Table `gamedb`.`filetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`filetype` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`filetype` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible file types';


-- -----------------------------------------------------
-- Table `gamedb`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`job` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`job` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `job_department` (`department_id` ASC) VISIBLE,
  CONSTRAINT `job_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `gamedb`.`department` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all positions in all departments of the Foundation';


-- -----------------------------------------------------
-- Table `gamedb`.`logindata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`logindata` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`logindata` (
  `login` VARCHAR(40) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status_id` INT NOT NULL,
  `expire` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`user_employeeClass_id`, `user_id`),
  UNIQUE INDEX `loginData_ak_1` (`login` ASC) VISIBLE,
  INDEX `loginData_status` (`status_id` ASC) VISIBLE,
  INDEX `loginData_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `loginData_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `gamedb`.`accessstatus` (`id`),
  CONSTRAINT `loginData_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all employee credentials';


-- -----------------------------------------------------
-- Table `gamedb`.`object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`object` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`object` (
  `id` INT NOT NULL,
  `nickname` VARCHAR(100) NOT NULL,
  `clearance_id` INT NOT NULL,
  `containmentClass_id` INT NOT NULL,
  `disruptionClass_id` INT NULL DEFAULT NULL,
  `riskClass_id` INT NULL DEFAULT NULL,
  `secondaryClass_id` INT NULL DEFAULT NULL,
  `facility_id` INT NULL DEFAULT NULL,
  `specialAccessRequired` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `object_clearance` (`clearance_id` ASC) VISIBLE,
  INDEX `object_containmentClass` (`containmentClass_id` ASC) VISIBLE,
  INDEX `object_disruptionClass` (`disruptionClass_id` ASC) VISIBLE,
  INDEX `object_facility` (`facility_id` ASC) VISIBLE,
  INDEX `object_riskClass` (`riskClass_id` ASC) VISIBLE,
  INDEX `object_secondaryClass` (`secondaryClass_id` ASC) VISIBLE,
  CONSTRAINT `object_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`),
  CONSTRAINT `object_containmentClass`
    FOREIGN KEY (`containmentClass_id`)
    REFERENCES `gamedb`.`containmentclass` (`id`),
  CONSTRAINT `object_disruptionClass`
    FOREIGN KEY (`disruptionClass_id`)
    REFERENCES `gamedb`.`disruptionclass` (`id`),
  CONSTRAINT `object_facility`
    FOREIGN KEY (`facility_id`)
    REFERENCES `gamedb`.`facility` (`id`),
  CONSTRAINT `object_riskClass`
    FOREIGN KEY (`riskClass_id`)
    REFERENCES `gamedb`.`riskclass` (`id`),
  CONSTRAINT `object_secondaryClass`
    FOREIGN KEY (`secondaryClass_id`)
    REFERENCES `gamedb`.`secondaryclass` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all objects contained by the Foundation';


-- -----------------------------------------------------
-- Table `gamedb`.`objectfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`objectfile` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`objectfile` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `docLink` VARCHAR(200) NOT NULL,
  `createdDateTime` DATETIME NOT NULL,
  `object_id` INT NOT NULL,
  `clearance_id` INT NULL DEFAULT NULL,
  `docType_id` INT NOT NULL,
  `specialAccessRequired` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`docLink`, `id`),
  INDEX `objectFile_clearance` (`clearance_id` ASC) VISIBLE,
  INDEX `objectFile_docType` (`docType_id` ASC) VISIBLE,
  INDEX `objectFile_object` (`object_id` ASC) VISIBLE,
  INDEX `objectFile_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `objectFile_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`),
  CONSTRAINT `objectFile_docType`
    FOREIGN KEY (`docType_id`)
    REFERENCES `gamedb`.`doctype` (`id`),
  CONSTRAINT `objectFile_object`
    FOREIGN KEY (`object_id`)
    REFERENCES `gamedb`.`object` (`id`),
  CONSTRAINT `objectFile_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all files directly related to objects';


-- -----------------------------------------------------
-- Table `gamedb`.`riskclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`riskclass` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`riskclass` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible risk classes';


-- -----------------------------------------------------
-- Table `gamedb`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`room` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`room` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `clearance_id` INT NOT NULL,
  `roomStatus_id` INT NOT NULL,
  `roomType_id` INT NOT NULL,
  `parentRoom_id` INT NULL DEFAULT NULL,
  `facilitySection_id` INT NOT NULL,
  `specialAccessRequired` TINYINT NOT NULL,
  `plan_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Room_clearance` (`clearance_id` ASC) VISIBLE,
  INDEX `room_facilitySection` (`facilitySection_id` ASC) VISIBLE,
  INDEX `room_room` (`parentRoom_id` ASC) VISIBLE,
  INDEX `room_roomStatus` (`roomStatus_id` ASC) VISIBLE,
  INDEX `room_roomType` (`roomType_id` ASC) VISIBLE,
  INDEX `room_userFile` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `Room_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`),
  CONSTRAINT `room_facilitySection`
    FOREIGN KEY (`facilitySection_id`)
    REFERENCES `gamedb`.`facilitysection` (`id`),
  CONSTRAINT `room_room`
    FOREIGN KEY (`parentRoom_id`)
    REFERENCES `gamedb`.`room` (`id`),
  CONSTRAINT `room_roomStatus`
    FOREIGN KEY (`roomStatus_id`)
    REFERENCES `gamedb`.`roomstatus` (`id`),
  CONSTRAINT `room_roomType`
    FOREIGN KEY (`roomType_id`)
    REFERENCES `gamedb`.`roomtype` (`id`),
  CONSTRAINT `room_userFile`
    FOREIGN KEY (`plan_id`)
    REFERENCES `gamedb`.`userfile` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all rooms in all sections of all facilities of the Foundation';


-- -----------------------------------------------------
-- Table `gamedb`.`roomstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`roomstatus` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`roomstatus` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible room statuses';


-- -----------------------------------------------------
-- Table `gamedb`.`roomtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`roomtype` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`roomtype` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible room types';


-- -----------------------------------------------------
-- Table `gamedb`.`secondaryclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`secondaryclass` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`secondaryclass` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible secondary classes';


-- -----------------------------------------------------
-- Table `gamedb`.`sectiontype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`sectiontype` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`sectiontype` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible section types';


-- -----------------------------------------------------
-- Table `gamedb`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`session` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`session` (
  `id` VARCHAR(255) NOT NULL,
  `accessStatus_id` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `expire` DATETIME NOT NULL,
  `loginData_user_employeeClass_id` INT NOT NULL,
  `loginData_user_id` INT NOT NULL,
  `system_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `session_accessStatus` (`accessStatus_id` ASC) VISIBLE,
  INDEX `session_loginData` (`loginData_user_employeeClass_id` ASC, `loginData_user_id` ASC) VISIBLE,
  INDEX `session_system` (`system_id` ASC) VISIBLE,
  CONSTRAINT `session_accessStatus`
    FOREIGN KEY (`accessStatus_id`)
    REFERENCES `gamedb`.`accessstatus` (`id`),
  CONSTRAINT `session_loginData`
    FOREIGN KEY (`loginData_user_employeeClass_id` , `loginData_user_id`)
    REFERENCES `gamedb`.`logindata` (`user_employeeClass_id` , `user_id`),
  CONSTRAINT `session_system`
    FOREIGN KEY (`system_id`)
    REFERENCES `gamedb`.`system` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all authorization sessions of the Foundation\'\'s employees';


-- -----------------------------------------------------
-- Table `gamedb`.`system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`system` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`system` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `purpose` TEXT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `clearance_id` INT NOT NULL,
  `documentation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `system_userFile` (`documentation_id` ASC) VISIBLE,
  INDEX `systems_clearance` (`clearance_id` ASC) VISIBLE,
  CONSTRAINT `system_userFile`
    FOREIGN KEY (`documentation_id`)
    REFERENCES `gamedb`.`userfile` (`id`),
  CONSTRAINT `systems_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all internal information systems of the Foundation';


-- -----------------------------------------------------
-- Table `gamedb`.`systemaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`systemaccess` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`systemaccess` (
  `systems_id` INT NOT NULL,
  `systemAccessRole_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`systems_id`, `user_employeeClass_id`, `user_id`, `systemAccessRole_id`),
  INDEX `systemAccess_systemAccessRole` (`systemAccessRole_id` ASC) VISIBLE,
  INDEX `systemAccess_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `systemAccess_systemAccessRole`
    FOREIGN KEY (`systemAccessRole_id`)
    REFERENCES `gamedb`.`systemaccessrole` (`id`),
  CONSTRAINT `systemAccess_systems`
    FOREIGN KEY (`systems_id`)
    REFERENCES `gamedb`.`system` (`id`),
  CONSTRAINT `systemAccess_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all `system` permissions';


-- -----------------------------------------------------
-- Table `gamedb`.`systemaccessrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`systemaccessrole` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`systemaccessrole` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records about possible user roles in the `system` (for example: user or administrator)';


-- -----------------------------------------------------
-- Table `gamedb`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`unit` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`unit` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of possible divisions, groups, units, etc. in which the employees of the Foundation are members';


-- -----------------------------------------------------
-- Table `gamedb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`user` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`user` (
  `id` INT NOT NULL,
  `gender` TINYINT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `rotationDate` DATE NULL DEFAULT NULL,
  `photoLink` VARCHAR(200) NULL DEFAULT NULL,
  `clearance_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `facility_id` INT NOT NULL,
  `employeeClass_id` INT NOT NULL,
  `decree_id` INT NULL DEFAULT NULL,
  `supervisor_id` INT NULL DEFAULT NULL,
  `supervisor_employeeClass_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `employeeClass_id`),
  INDEX `user_clearance` (`clearance_id` ASC) VISIBLE,
  INDEX `user_employeeClass` (`employeeClass_id` ASC) VISIBLE,
  INDEX `user_facility` (`facility_id` ASC) VISIBLE,
  INDEX `user_job` (`job_id` ASC) VISIBLE,
  INDEX `user_user` (`supervisor_id` ASC, `supervisor_employeeClass_id` ASC) VISIBLE,
  INDEX `user_userFile` (`decree_id` ASC) VISIBLE,
  CONSTRAINT `user_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`),
  CONSTRAINT `user_employeeClass`
    FOREIGN KEY (`employeeClass_id`)
    REFERENCES `gamedb`.`employeeclass` (`id`),
  CONSTRAINT `user_facility`
    FOREIGN KEY (`facility_id`)
    REFERENCES `gamedb`.`facility` (`id`),
  CONSTRAINT `user_job`
    FOREIGN KEY (`job_id`)
    REFERENCES `gamedb`.`job` (`id`),
  CONSTRAINT `user_user`
    FOREIGN KEY (`supervisor_id` , `supervisor_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`),
  CONSTRAINT `user_userFile`
    FOREIGN KEY (`decree_id`)
    REFERENCES `gamedb`.`userfile` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all the Foundation\'\'s staff';


-- -----------------------------------------------------
-- Table `gamedb`.`userfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`userfile` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`userfile` (
  `id` INT NOT NULL,
  `name` INT NOT NULL,
  `clearance_id` INT NOT NULL,
  `createdDateTime` DATETIME NOT NULL,
  `docLink` INT NOT NULL,
  `fileType_id` INT NOT NULL,
  `creator_id` INT NOT NULL,
  `creator_employeeClass_id` INT NOT NULL,
  `associated_with_id` INT NULL DEFAULT NULL,
  `associated_with_employeeClass_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `userFile_clearance` (`clearance_id` ASC) VISIBLE,
  INDEX `userFile_fileType` (`fileType_id` ASC) VISIBLE,
  INDEX `userFile_user_associated` (`associated_with_id` ASC, `associated_with_employeeClass_id` ASC) VISIBLE,
  INDEX `userFile_user_creator` (`creator_id` ASC, `creator_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `userFile_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`),
  CONSTRAINT `userFile_fileType`
    FOREIGN KEY (`fileType_id`)
    REFERENCES `gamedb`.`filetype` (`id`),
  CONSTRAINT `userFile_user_associated`
    FOREIGN KEY (`associated_with_id` , `associated_with_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`),
  CONSTRAINT `userFile_user_creator`
    FOREIGN KEY (`creator_id` , `creator_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all user files of the Foundation';


-- -----------------------------------------------------
-- Table `gamedb`.`userfilespecialaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`userfilespecialaccess` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`userfilespecialaccess` (
  `userFile_id` INT NOT NULL,
  `createdDateTime` DATETIME NOT NULL,
  `expiryDateTime` DATETIME NOT NULL,
  `decree_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`userFile_id`, `user_id`, `user_employeeClass_id`),
  INDEX `userFileSpecialAccess_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  INDEX `userFileSpecialAccess_userFile_decree` (`decree_id` ASC) VISIBLE,
  CONSTRAINT `userFileSpecialAccess_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`),
  CONSTRAINT `userFileSpecialAccess_userFile`
    FOREIGN KEY (`userFile_id`)
    REFERENCES `gamedb`.`userfile` (`id`),
  CONSTRAINT `userFileSpecialAccess_userFile_decree`
    FOREIGN KEY (`decree_id`)
    REFERENCES `gamedb`.`userfile` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all special access permissions of employees to files';


-- -----------------------------------------------------
-- Table `gamedb`.`userobjectspecialaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`userobjectspecialaccess` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`userobjectspecialaccess` (
  `object_id` INT NOT NULL,
  `clearance_id` INT NOT NULL,
  `createdDateTime` DATETIME NOT NULL,
  `expiryDateTime` DATETIME NOT NULL,
  `decree_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`clearance_id`, `object_id`, `user_id`, `user_employeeClass_id`),
  INDEX `addClearToUser_object` (`object_id` ASC) VISIBLE,
  INDEX `userObjectAdditionalAccess_userFile` (`decree_id` ASC) VISIBLE,
  INDEX `userObjectSpecialAccess_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `addClearToUser_clearance`
    FOREIGN KEY (`clearance_id`)
    REFERENCES `gamedb`.`clearance` (`id`),
  CONSTRAINT `addClearToUser_object`
    FOREIGN KEY (`object_id`)
    REFERENCES `gamedb`.`object` (`id`),
  CONSTRAINT `userObjectAdditionalAccess_userFile`
    FOREIGN KEY (`decree_id`)
    REFERENCES `gamedb`.`userfile` (`id`),
  CONSTRAINT `userObjectSpecialAccess_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all special access permissions of employees to objects';


-- -----------------------------------------------------
-- Table `gamedb`.`userroomspecialaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`userroomspecialaccess` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`userroomspecialaccess` (
  `room_id` INT NOT NULL,
  `createdDateTime` DATETIME NOT NULL,
  `expiryDateTime` DATETIME NOT NULL,
  `decree_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`room_id`, `user_employeeClass_id`, `user_id`),
  INDEX `userRoomAdditionalAccess_userFile` (`decree_id` ASC) VISIBLE,
  INDEX `userRoomSpecialAccess_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `userRoomAdditionalAccess_Room`
    FOREIGN KEY (`room_id`)
    REFERENCES `gamedb`.`room` (`id`),
  CONSTRAINT `userRoomAdditionalAccess_userFile`
    FOREIGN KEY (`decree_id`)
    REFERENCES `gamedb`.`userfile` (`id`),
  CONSTRAINT `userRoomSpecialAccess_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all special access permissions of employees to rooms';


-- -----------------------------------------------------
-- Table `gamedb`.`usersectionspecialaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`usersectionspecialaccess` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`usersectionspecialaccess` (
  `facilitySection_id` INT NOT NULL,
  `createdDateTime` DATETIME NOT NULL,
  `expiryDateTime` DATETIME NOT NULL,
  `decree_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`facilitySection_id`, `user_id`, `user_employeeClass_id`),
  INDEX `userSectionSpecialAccess_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  INDEX `userSectionSpecialAccess_userFile` (`decree_id` ASC) VISIBLE,
  CONSTRAINT `userSectionSpecialAccess_facilitySection`
    FOREIGN KEY (`facilitySection_id`)
    REFERENCES `gamedb`.`facilitysection` (`id`),
  CONSTRAINT `userSectionSpecialAccess_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`),
  CONSTRAINT `userSectionSpecialAccess_userFile`
    FOREIGN KEY (`decree_id`)
    REFERENCES `gamedb`.`userfile` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all special access permissions of employees to rooms';


-- -----------------------------------------------------
-- Table `gamedb`.`usertoobject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`usertoobject` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`usertoobject` (
  `object_id` INT NOT NULL,
  `userToObjectRole_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`object_id`, `user_id`, `user_employeeClass_id`),
  INDEX `userToObject_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  INDEX `userToObject_userToObjectStatus` (`userToObjectRole_id` ASC) VISIBLE,
  CONSTRAINT `userToObject_object`
    FOREIGN KEY (`object_id`)
    REFERENCES `gamedb`.`object` (`id`),
  CONSTRAINT `userToObject_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`),
  CONSTRAINT `userToObject_userToObjectStatus`
    FOREIGN KEY (`userToObjectRole_id`)
    REFERENCES `gamedb`.`usertoobjectrole` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records of all user-to-object relationships';


-- -----------------------------------------------------
-- Table `gamedb`.`usertoobjectrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`usertoobjectrole` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`usertoobjectrole` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records about possible employees roles in relation to the objects (for example: researcher or curator)';


-- -----------------------------------------------------
-- Table `gamedb`.`usertounit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamedb`.`usertounit` ;

CREATE TABLE IF NOT EXISTS `gamedb`.`usertounit` (
  `unit_id` INT NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `user_employeeClass_id` INT NOT NULL,
  PRIMARY KEY (`unit_id`, `user_employeeClass_id`, `user_id`),
  INDEX `userToUnit_user` (`user_id` ASC, `user_employeeClass_id` ASC) VISIBLE,
  CONSTRAINT `userToUnit_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `gamedb`.`unit` (`id`),
  CONSTRAINT `userToUnit_user`
    FOREIGN KEY (`user_id` , `user_employeeClass_id`)
    REFERENCES `gamedb`.`user` (`id` , `employeeClass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table stores records about possible employees roles in relation to the units (divisions, groups, etc.)(for example: Commander, Deputy Commander or Officer)';

USE `scpdnd` ;

-- -----------------------------------------------------
-- Table `scpdnd`.`audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`audio` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`audio` (
  `audio_id` INT NOT NULL AUTO_INCREMENT,
  `uploader_id` INT NOT NULL,
  `upload_date` DATETIME NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `file_link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`audio_id`),
  INDEX `uploader_id` (`uploader_id` ASC) VISIBLE,
  CONSTRAINT `uploaderAudio`
    FOREIGN KEY (`uploader_id`)
    REFERENCES `scpdnd`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`auth_group` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`auth_group_permissions` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `scpdnd`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `scpdnd`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`auth_permission` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `scpdnd`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 93
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`auth_user_groups` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`auth_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `scpdnd`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `scpdnd`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`auth_user_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`auth_user_user_permissions` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`auth_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `scpdnd`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `scpdnd`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`character` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`character` (
  `character_id` INT NOT NULL AUTO_INCREMENT,
  `creator_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `content` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`character_id`),
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  INDEX `game_id` (`game_id` ASC) VISIBLE,
  CONSTRAINT `creatorCharacter`
    FOREIGN KEY (`creator_id`)
    REFERENCES `scpdnd`.`user` (`user_id`),
  CONSTRAINT `gameCharacter`
    FOREIGN KEY (`game_id`)
    REFERENCES `scpdnd`.`game` (`game_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`django_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`django_admin_log` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `scpdnd`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `scpdnd`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`django_content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`django_content_type` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`django_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`django_migrations` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`django_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`django_session` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`document` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`document` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `uploader_id` INT NOT NULL,
  `upload_date` DATETIME NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `file_link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`document_id`),
  INDEX `uploader_id` (`uploader_id` ASC) VISIBLE,
  CONSTRAINT `uploaderDocument`
    FOREIGN KEY (`uploader_id`)
    REFERENCES `scpdnd`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`game` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`game` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `next_session_date` DATETIME NULL DEFAULT NULL,
  `creator_id` INT NOT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `creatorGame`
    FOREIGN KEY (`creator_id`)
    REFERENCES `scpdnd`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`image` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`image` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `uploader_id` INT NOT NULL,
  `upload_date` DATETIME NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `file_link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `uploader_id` (`uploader_id` ASC) VISIBLE,
  CONSTRAINT `uploaderImage`
    FOREIGN KEY (`uploader_id`)
    REFERENCES `scpdnd`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`participant` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`participant` (
  `game_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `isGM` TINYINT NOT NULL,
  PRIMARY KEY (`game_id`, `user_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `gameParticipant`
    FOREIGN KEY (`game_id`)
    REFERENCES `scpdnd`.`game` (`game_id`),
  CONSTRAINT `userParticipant`
    FOREIGN KEY (`user_id`)
    REFERENCES `scpdnd`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scpdnd`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scpdnd`.`user` ;

CREATE TABLE IF NOT EXISTS `scpdnd`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
